<?php
 include("../config/settings.inc.php");

 include("$rootpath/include/header.php");
?>

<table>
<tr><td width="200px" style="background: #eee;" valign="top">

<!-- Team -->
<div class="sidebar-item">
<h3>Iowa CoCoRaHS Team</h3>

<b>State Coordinators</b>
<ul>
 <li><a href="mailto:akrherz@iastate.edu">Daryl Herzmann</a>, Iowa State</li>
 <li><a href="mailto:Barbara.Mayes@noaa.gov">Barb Mayes</a>, NWS Davenport</li>
</ul>

<p><b>Regional Coordinators</b>
<ul>
 <li><a href="mailto:Jeff.Boyne@noaa.gov">Jeff Boyne</a>, NWS La Crosse</li>
 <li><a href="mailto:Craig.Cogil@noaa.gov">Craig Cogil</a>, NWS Des Moines</li>
 <li><a href="mailto:Robert.Deroy@noaa.gov">Rob Deroy</a>, NWS Des Moines</li>
 <li><a href="mailto:Andy.Ervin@noaa.gov">Andy Ervin</a>, NWS Davenport</li>
 <li><a href="mailto:Brad.Fillbach@noaa.gov">Brad Fillbach</a>, NWS Des Moines</li>
 <li><a href="mailto:Mike.Gillispie@noaa.gov">Mike Gillispie</a>, NWS Sioux Falls</li>
</ul>

</div>

</td><td width="600px">
<div style="margin-left: 20px;">The <b>Co</b>mmunity <b>Co</b>llaborative
<b>Ra</b>in, <b>H</b>ail and <b>S</b>now Network (CoCoRaHS) is a grassroots 
volunteer network of backyard weather observers of all ages and backgrounds 
working together to measure and map precipitation (rain, hail and snow) in 
their local communities.
</div>

<h3>How can I get involved?</h3>
<ul>
 <li>Step 1: <a href="http://www.cocorahs.org/Application.aspx">Become a CoCoRaHS Observer</a></li>
 <li>Step 2: Become trained to take observations.  You can either take
  the <a href="http://www.cocorahs.org/Media/docs/CoCoRaHS_Training_4.5.pdf">On-line training</a> or attend local training sessions to be announced later.</li>
 <li>Step 3: Purchase an official 4" Rain Gauge.
  <br />Available at: <a href="http://www.professionalraingauge.com/">ProfessionalRainGauge.com</a>, <a href="http://www.weatheryourway.com/cocorahs/store.html">WeatherYourWay.com</a>, or <a href="http://www.ambientweather.com/strgloteprra.html">AmbientWeather</a> for 22 dollars.</li>
</ul>

<p>You are then ready to start submitting your daily reports online!

<h3>News</h3>
<img src="http://www.cocorahs.org/Media/Images/IOWAaugust1stSMALL.jpg">

</td></tr>
</table>


<?php include("$rootpath/include/footer.php"); ?>
